"""empty message

Revision ID: 2640700776f0
Revises: f32f5cd0611a
Create Date: 2024-06-09 06:31:09.378256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2640700776f0'
down_revision = 'f32f5cd0611a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_user_post', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_post', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
